name: Check python code

on:
  push:
    paths:
    - '**.py'
    - '.github/workflows/check_python_code.yml'

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipenv
    - name: Apply isort, black, and flake8
      run: |
        pip install isort black flake8 flake8-docstrings
        isort --check-only .
        black --check .
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pipenv install pytest
        pipenv run pytest
