name: Update lambda function

on:
  push:
    branches:
    - master
    paths:
    - lambda/**
    - .github/workflows/upload_lambda_function.yml

jobs:
  update-lambda-function:
    runs-on: ubuntu-latest
    env:
      LAMBDA_DIR: worklog_notifier_lambda
      FUNCTION_NAME: ${{ secrets.FUNCTION_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-northeast-1
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install -U awscli
    - name: Apply isort, black, and flake8
      run: |
        pip install isort black flake8 flake8-docstrings
        isort --check-only .
        black --check .
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Create zip
      run: |
        apt-get update && apt-get install -y zip
        cd lambda || exit
        pip install --target=packages -r requirements.txt
        cd packages || exit
        zip -r9 ../function.zip .
        cd .. || exit
        zip -g function.zip lambda_monday.py
        cd .. || exit
        zip -gr lambda/function.zip monday_stats
    - name: Update lambda function
      run: |
        pip install awscli
        aws lambda update-function-code \
            --function-name  "${FUNCTION_NAME}" \
            --zip-file fileb://lambda/function.zip > /dev/null
