name: Check python code

on:
  push:
    branches:
    - master
    paths:
    - lambda/**
    - .github/workflows/upload_lambda_function.yml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install -U awscli
    - name: Lint with flake8
      run: |
        pip install flake8 flake8-docstrings
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Create zip
      run: |
        apt-get update && apt-get install -y zip
        cd lambda || exit
        pip install --target=packages -r requirements.txt
        cd packages || exit
        zip -r9 ../function.zip .
        cd .. || exit
        zip -g function.zip lambda_monday.py
        cd .. || exit
        zip -gr lambda/function.zip monday_stats
